package bundle

import "regexp"

// Platform resources (DESIGN.md "M2"): one shared Postgres and one shared S3
// server per host, run by the node as the compose project lwd-platform on the
// docker network PlatformNetwork. The controller owns resource names and
// credentials; the node executes idempotent provisioning, backup and restore.

// PlatformNetwork is the external docker network every platform service and
// every service of a Bundle with Platform set is attached to.
const PlatformNetwork = "lwd-platform"

// In-network endpoints of the platform services, as seen by app containers.
const (
	PostgresHost = "lwd-postgres"
	PostgresPort = 5432
	S3Endpoint   = "http://lwd-s3:3900"
	S3Region     = "garage"
)

// Variables injected by the controller for `database = true` and
// `storage = true`. Applications may not define them themselves.
var (
	DatabaseVars = []string{"DATABASE_URL"}
	StorageVars  = []string{"S3_ENDPOINT", "S3_REGION", "S3_BUCKET", "S3_ACCESS_KEY_ID", "S3_SECRET_ACCESS_KEY"}
)

var (
	// DatabaseNameRE is a Postgres database and role name the node accepts.
	// It is also a safe unquoted SQL identifier.
	DatabaseNameRE = regexp.MustCompile(`^[a-z][a-z0-9_]{0,62}$`)
	// BucketNameRE is an S3 bucket name the node accepts.
	BucketNameRE = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{2,62}$`)
	// PasswordRE is a database password the node accepts: generated by the
	// controller, it never needs quoting in SQL or URLs.
	PasswordRE = regexp.MustCompile(`^[A-Za-z0-9_-]{24,128}$`)
	// AccessKeyIDRE is a Garage access key id.
	AccessKeyIDRE = regexp.MustCompile(`^GK[0-9a-f]{24}$`)
	// BackupFileRE is the base name of a database backup on a node.
	BackupFileRE = regexp.MustCompile(`^[0-9]{8}T[0-9]{6}\.[0-9]{3}Z\.dump$`)
)

// DatabaseRequest is the body of PUT /v1/platform/databases/{name}.
type DatabaseRequest struct {
	Password string `json:"password"`
}

// BucketRequest is the body of PUT /v1/platform/buckets/{name}. AccessKeyID
// is the key the controller already holds for the bucket, if any; the node
// keeps it when it still exists and creates a new key otherwise.
type BucketRequest struct {
	AccessKeyID string `json:"access_key_id,omitempty"`
}

// BucketCredentials is the node's answer to a bucket PUT.
type BucketCredentials struct {
	AccessKeyID     string `json:"access_key_id"`
	SecretAccessKey string `json:"secret_access_key"`
}

// BackupFile is one database backup on a node.
type BackupFile struct {
	File      string `json:"file"` // base name, matches BackupFileRE
	Bytes     int64  `json:"bytes"`
	SHA256    string `json:"sha256,omitempty"` // set by backup; not by list
	CreatedAt string `json:"created_at"`       // RFC3339, UTC
}

// RestoreRequest is the body of POST /v1/platform/databases/{name}/restore:
// restore File into the database, stopping app/env's live project meanwhile.
type RestoreRequest struct {
	File string `json:"file"`
	App  string `json:"app"`
	Env  string `json:"env"`
}

// RestoreResult reports what a restore did and how long each step took.
type RestoreResult struct {
	File      string `json:"file"`
	Stopped   bool   `json:"stopped"` // a live project was stopped and started again
	StopMS    int64  `json:"stop_ms"`
	RestoreMS int64  `json:"restore_ms"`
	StartMS   int64  `json:"start_ms"`
	TotalMS   int64  `json:"total_ms"`
}
